### ISSUE TITLE
Copy link option doesn't work on Fixed Mode

### ISSUE THREAD

**Issue by paodb** [parsagholipour/sharee#4]
Link is not being copied for Fixed mode. Method `listenDriverEvents` should be defined and called in FixedStrategy as it is in [NormalStrategy](https://github.com/parsagholipour/sharee/blob/50e9cea355f56fd07b5a83ea8e4e8ac478dcb364/src/lib/strategies/NormalStrategy.ts#L131).

**Comment by parsagholipour** [comment]
Fixed https://github.com/parsagholipour/sharee/commit/2b7bcfa65e3b3742d83b3e3065a583f0f5550ed2#diff-6cc8e1187819dec8cc739978473ed4e9929b5fdae43aa17a6c9480d846e002db

**Comment by paodb** [comment]
Is release 1.1.3 available on NPM?
